# Generated by Django 2.2.7 on 2019-11-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_id', models.CharField(max_length=100)),
                ('comment_text', models.CharField(max_length=300)),
                ('create_date_time', models.DateTimeField()),
                ('rank', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_fri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_mon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_sun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_thu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_tue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_update',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_wed',
            field=models.IntegerField(default=0),
        ),
    ]
